version: '3.8'

services:
    mssql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "pw123456"
            MSSQL_PID: "Developer"
        volumes:
            - ./.mssql_data:/var/opt/mssql

    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
            - "10000:10000"
            - "10001:10001"
            - "10002:10002"
        volumes:
            - ./.azurite_data:/data
