version: '3.8'

services:
    mssql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "BugRepro202503"
            MSSQL_PID: "Developer"
            MSSQL_COLLATION: "Latin1_General_100_BIN2_UTF8"
        volumes:
            - mssql_data:/var/opt/mssql
        healthcheck:
            test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools18/bin/sqlcmd -S . -U sa -P BugRepro202503 -C"]
            interval: 30s
            timeout: 30s
            retries: 5
            start_period: 15s

    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
            - "10000:10000"
            - "10001:10001"
            - "10002:10002"
        volumes:
            - azurite_data:/data

volumes:
    mssql_data:
    azurite_data:
